import AppKit

@MainActor public final class ClipboardMonitor {
    private let pasteboard: NSPasteboard
    private let onChange: (String?) -> Void
    private var timer: Timer?
    private var lastChange: Int
    private var capturingSelection = false
    private static let protectedTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"), .init("com.agilebits.onepassword")
    ]
    public var onAccessBlocked: (() -> Void)?

    public init(pasteboard: NSPasteboard, onChange: @escaping (String?) -> Void) {
        self.pasteboard = pasteboard
        self.onChange = onChange
        self.lastChange = pasteboard.changeCount
    }

    public var automaticAccessAllowed: Bool {
        if #available(macOS 15.4, *) {
            return pasteboard.accessBehavior != .alwaysDeny && pasteboard.accessBehavior != .ask
        }
        return true
    }

    public func start() {
        stop()
        lastChange = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.poll() }
        }
        timer.tolerance = 0.1
        self.timer = timer
        RunLoop.main.add(timer, forMode: .common)
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    public func poll() {
        guard timer != nil, !capturingSelection else { return }
        guard automaticAccessAllowed else {
            stop()
            onAccessBlocked?()
            return
        }
        let change = pasteboard.changeCount
        guard change != lastChange else { return }
        lastChange = change
        let text = currentText()
        // A promised representation can change while another app supplies it.
        // Discard that snapshot and pick up the newer clipboard on the next tick.
        guard pasteboard.changeCount == change else { return }
        onChange(text)
    }

    public func copyTranslation(_ text: String) -> Bool {
        guard !text.isEmpty else { return false }
        pasteboard.clearContents()
        let success = pasteboard.setString(text, forType: .string)
        lastChange = pasteboard.changeCount
        return success
    }

    public func currentText() -> String? {
        if #available(macOS 15.4, *), pasteboard.accessBehavior == .alwaysDeny { return nil }
        guard Self.protectedTypes.isDisjoint(with: pasteboard.types ?? []) else { return nil }
        return pasteboard.string(forType: .string)
    }

    /// A shortcut handles this clipboard change before the next automatic poll.
    public func currentTextForManualAction() -> String? {
        let change = pasteboard.changeCount
        let text = currentText()
        guard pasteboard.changeCount == change else { return nil }
        lastChange = change
        return text
    }

    public func acknowledgeCurrentChange() {
        lastChange = pasteboard.changeCount
    }

    /// Invokes a selection-only Copy action. The copied source stays on the clipboard.
    /// A fresh write must match the independently identified message before use.
    public func captureSelectionCopy(copy: () -> Bool, isSourceActive: () -> Bool,
                                     matchesSource: (String) -> Bool,
                                     timeout: Duration = .seconds(1)) async throws -> String {
        guard !capturingSelection, automaticAccessAllowed, isSourceActive(),
              Self.protectedTypes.isDisjoint(with: pasteboard.types ?? []) else { throw SelectionCopyError.unavailable }
        let originalChange = pasteboard.changeCount
        capturingSelection = true
        defer { capturingSelection = false }
        try Task.checkCancellation()
        guard copy() else { throw SelectionCopyError.unavailable }
        let deadline = ContinuousClock.now + timeout
        repeat {
            try Task.checkCancellation()
            guard isSourceActive() else { throw SelectionCopyError.unavailable }
            let change = pasteboard.changeCount
            if change != originalChange {
                guard let text = currentText(), !text.isEmpty, text.count <= 10_000,
                      matchesSource(text), pasteboard.changeCount == change,
                      isSourceActive() else { throw SelectionCopyError.unavailable }
                try Task.checkCancellation()
                lastChange = change
                return text
            }
            try await Task.sleep(for: .milliseconds(20))
        } while ContinuousClock.now < deadline
        throw SelectionCopyError.unavailable
    }
}

public enum SelectionCopyError: Error { case unavailable }
